<?php

namespace App\Models;

use App\Enums\LocationMode;
use App\Enums\ReportPriority;
use App\Enums\ReportStatus;
use Database\Factories\ReportFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

#[Fillable([
    'client_id', 'category_id', 'name', 'description', 'status', 'priority',
    'ai_priority', 'ai_priority_calculated_at', 'ai_priority_reason',
    'location_mode', 'location_lat', 'location_lng', 'location_accuracy',
    'location_address', 'location_updated_at', 'assigned_admin_id',
    'assigned_staff_id', 'queued_at', 'assigned_at', 'first_response_at',
    'closed_at', 'closed_by_user_id', 'close_reason', 'metadata',
])]
class Report extends Model
{
    /** @use HasFactory<ReportFactory> */
    use HasFactory, SoftDeletes;

    /** Generated by Postgres — never written by the application. */
    protected $guarded = ['priority_weight', 'reference'];

    protected function casts(): array
    {
        return [
            'status' => ReportStatus::class,
            'priority' => ReportPriority::class,
            'location_mode' => LocationMode::class,
            'priority_weight' => 'integer',
            'ai_priority' => 'decimal:2',
            'ai_priority_reason' => 'array',
            'metadata' => 'array',
            'ai_priority_calculated_at' => 'datetime',
            'location_updated_at' => 'datetime',
            'queued_at' => 'datetime',
            'assigned_at' => 'datetime',
            'first_response_at' => 'datetime',
            'closed_at' => 'datetime',
        ];
    }

    protected static function booted(): void
    {
        static::creating(function (Report $report): void {
            // Drawn from the Postgres sequence before insert, so the value is
            // available on the model without an extra round trip.
            $report->reference ??= sprintf(
                'ZG-%s-%06d',
                now()->format('Y'),
                DB::selectOne("SELECT nextval('reports_reference_seq') AS n")->n,
            );

            // Entering the global queue is what queued_at records.
            $report->queued_at ??= now();
        });
    }

    /** @return BelongsTo<User, $this> */
    public function client(): BelongsTo
    {
        return $this->belongsTo(User::class, 'client_id');
    }

    /** @return BelongsTo<Category, $this> */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /** @return BelongsTo<User, $this> */
    public function assignedAdmin(): BelongsTo
    {
        return $this->belongsTo(User::class, 'assigned_admin_id');
    }

    /** @return BelongsTo<User, $this> */
    public function assignedStaff(): BelongsTo
    {
        return $this->belongsTo(User::class, 'assigned_staff_id');
    }

    /** @return BelongsTo<User, $this> */
    public function closedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'closed_by_user_id');
    }

    public function isOpen(): bool
    {
        return ! $this->status->isTerminal();
    }

    public function hasLiveLocation(): bool
    {
        return $this->location_mode === LocationMode::Streaming && $this->isOpen();
    }

    /** @return HasMany<Request, $this> */
    public function requests(): HasMany
    {
        return $this->hasMany(Request::class)->orderBy('sequence')->orderBy('id');
    }

    /** A report may auto-close once this returns false (CLAUDE.md section 6). */
    public function hasOpenRequests(): bool
    {
        return $this->requests()->open()->exists();
    }

    /** @return HasMany<ReportStatusHistory, $this> */
    public function statusHistories(): HasMany
    {
        return $this->hasMany(ReportStatusHistory::class)->orderBy('created_at')->orderBy('id');
    }

    /** @return HasMany<ReportRevision, $this> */
    public function revisions(): HasMany
    {
        return $this->hasMany(ReportRevision::class)->orderByDesc('created_at');
    }

    /** @return HasMany<ReportAssignment, $this> */
    public function assignments(): HasMany
    {
        return $this->hasMany(ReportAssignment::class)->orderByDesc('assigned_at');
    }

    /** @return HasMany<Attachment, $this> */
    public function attachments(): HasMany
    {
        return $this->hasMany(Attachment::class)->orderByDesc('created_at');
    }

    /** Voice notes only — rendered with a player in the staff view. @return HasMany<Attachment, $this> */
    public function voiceNotes(): HasMany
    {
        return $this->attachments()->voiceNotes();
    }

    /** @return HasMany<LocationStream, $this> */
    public function locationStreams(): HasMany
    {
        return $this->hasMany(LocationStream::class)->orderByDesc('started_at');
    }

    /** The session currently transmitting, if any. @return HasOne<LocationStream, $this> */
    public function activeLocationStream(): HasOne
    {
        return $this->hasOne(LocationStream::class)->whereNull('ended_at');
    }

    /** @return HasMany<LocationPing, $this> */
    public function locationPings(): HasMany
    {
        return $this->hasMany(LocationPing::class)->orderBy('recorded_at');
    }

    /** Drives the pin on the field worker's map. @return HasOne<LocationPing, $this> */
    public function latestLocationPing(): HasOne
    {
        return $this->hasOne(LocationPing::class)->latestOfMany('recorded_at');
    }

    /** @return HasMany<MediaStreamSession, $this> */
    public function mediaStreamSessions(): HasMany
    {
        return $this->hasMany(MediaStreamSession::class)->orderByDesc('created_at');
    }

    /** @return HasMany<MediaStreamSession, $this> */
    public function liveMediaStreams(): HasMany
    {
        return $this->mediaStreamSessions()->live();
    }
}
