/// <reference types="expo/types" />

// Ambient types for Expo assets, CSS modules and EXPO_PUBLIC_* env vars.
// Committed on purpose: `expo-env.d.ts` is generated by `expo start` and gitignored,
// so without this file `npm run typecheck` would fail on a fresh clone.
